---
title: "Homework 3"
author: Jingyi Zhang
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))
          
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Problem 1

## Problem 2

```{r tidy_dataset}
accel_df = 
  read_csv("./data/accel_data.csv") %>%
  janitor::clean_names() %>%
  mutate(
    day = factor(day),
    weekday = case_when(
      day == "Monday" ~ "Monday",
      day == "Tuesday" ~ "Tuesday",
      day == "Wednesday" ~ "Wednesday",
      day == "Thursday" ~ "Thursday",
      day == "Friday" ~ "Friday"),
    weekend = case_when(
      day == "Saturday" ~ "Saturday",
      day == "Sunday" ~ "Sunday")
    ) %>%
  pivot_longer(
    activity_1:activity_1440,
    names_to = "minute",
    names_prefix = "activity_",
    values_to = "activity_counts"
  )
```










